import pygame as pg

# Colors
DARK_GREEN = (4, 138, 129)
GREEN = (6, 214, 160)
BLUE = (84, 198, 235)
PURPLE = (138, 137, 192)
PINK = (205, 162, 171)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Fonts
FONT = "Consolas"

# Window
WINDOW_HEIGHT = 700
WINDOW_WIDTH = 1000

# Pygame events
COMPUTER_CLK = pg.USEREVENT
TOGGLE_EDITOR = pg.USEREVENT + 1

# Control bar
CONTROL_BAR_HEIGHT = 50
CONTROL_BAR_X = 0
CONTROL_BAR_BUTTON_HEIGHT = (int)(CONTROL_BAR_HEIGHT * 0.6)
CONTROL_BAR_BUTTON_Y = (int)(CONTROL_BAR_HEIGHT * 0.2)

# Instructions text input
ITI_OFFSET_X = 10
ITI_OFFSET_Y = 10
ITI_TEXT_AREA_HEIGHT = WINDOW_HEIGHT - (ITI_OFFSET_Y * 7)
ITI_TEXT_AREA_WIDTH = WINDOW_WIDTH - (ITI_OFFSET_X * 2)

# Processor
PROCESSOR_X = 10
PROCESSOR_Y = 10
PROCESSOR_WIDTH = 300
PROCESSOR_HEIGHT = PROCESSOR_WIDTH
PROCESSOR_CYCLES = ["FETCH", "DECODE", "EXECUTE", "MEMORY", "WRITEBACK"]

# ALU
ALU_X = 30
ALU_Y = 60
ALU_WIDTH = 100
ALU_HEIGHT = 100
ALU_INPUT_WIDTH = ALU_WIDTH * 0.4
ALU_INPUT_HEIGHT = 20
ALU_INPUT_Y = -ALU_INPUT_HEIGHT - 10
ALU_OUTPUT_Y = ALU_HEIGHT + 10

# Control Unit
CONTROL_UNIT_X = ALU_X + ALU_WIDTH + 40
CONTROL_UNIT_Y = ALU_Y + ALU_INPUT_Y
CONTROL_UNIT_WIDTH = 100
CONTROL_UNIT_HEIGHT = 100

# PC
PC_X = CONTROL_UNIT_X
PC_WIDTH = (CONTROL_UNIT_WIDTH / 2) - 5
PC_HEIGHT = 20
PC_Y = CONTROL_UNIT_Y + CONTROL_UNIT_HEIGHT + 10

# MBR
MBR_X = PC_X + PC_WIDTH + 10
MBR_WIDTH = PC_WIDTH
MBR_Y = PC_Y
MBR_HEIGHT = PC_HEIGHT

# MAR
MAR_X = PC_X
MAR_WIDTH = PC_WIDTH
MAR_Y = PC_Y + PC_HEIGHT + 10
MAR_HEIGHT = PC_HEIGHT

# IR
IR_X = MBR_X
IR_WIDTH = PC_WIDTH
IR_Y = MAR_Y
IR_HEIGHT = PC_HEIGHT

# General Records
GENERAL_RECORDS_LENGTH = 8
GENERAL_RECORDS_X = PC_X
GENERAL_RECORDS_Y = MAR_Y + MAR_HEIGHT + 10
GENERAL_RECORDS_WIDTH = PC_WIDTH + 5
GENERAL_RECORDS_HEIGHT = PC_HEIGHT

# BUS
BUS_WIDTH = 2
SYSTEM_BUS_ADDRESS_INDEX = 0
SYSTEM_BUS_DATA_INDEX = 1
SYSTEM_BUS_CONTROL_INDEX = 2

# Instruction
