import pygame as pg

# Colors
DARK_GREEN = (4, 138, 129)
GREEN = (6, 214, 160)
BLUE = (84, 198, 235)
PURPLE = (138, 137, 192)
PINK = (205, 162, 171)

# Window
WINDOW_HEIGHT = 700
WINDOW_WIDTH = 1000

# Pygame events
COMPUTER_CLK = pg.USEREVENT
TOGGLE_EDITOR = pg.USEREVENT + 1

# Control bar
CONTROL_BAR_HEIGHT = 50
CONTROL_BAR_X = 0
CONTROL_BAR_BUTTON_HEIGHT = (int)(CONTROL_BAR_HEIGHT * 0.6)
CONTROL_BAR_BUTTON_Y = (int)(CONTROL_BAR_HEIGHT * 0.2)

# Instructions text input
ITI_OFFSET_X = 10
ITI_OFFSET_Y = 10
ITI_TEXT_AREA_HEIGHT = WINDOW_HEIGHT - (ITI_OFFSET_Y * 7)
ITI_TEXT_AREA_WIDTH = WINDOW_WIDTH - (ITI_OFFSET_X * 2)

# Processor
GENERAL_RECORDS_LENGTH = 8
PROCESSOR_X = 10
PROCESSOR_Y = 10
PROCESSOR_WIDTH = 300
PROCESSOR_HEIGHT = 300
