import pygame as pg

# Pygame events
COMPUTER_CLK = pg.USEREVENT
TOGGLE_EDITOR = pg.USEREVENT + 1


# Control bar
CONTROL_BAR_HEIGHT = 50
CONTROL_BAR_X = 0
CONTROL_BAR_BUTTON_HEIGHT = (int)(CONTROL_BAR_HEIGHT * 0.6)
CONTROL_BAR_BUTTON_Y = (int)(CONTROL_BAR_HEIGHT * 0.2)

# Instructions text input
ITI_OFFSET_X = 50
ITI_OFFSET_Y = 50
ITI_TEXT_AREA_HEIGHT = 300
ITI_TEXT_AREA_WIDTH = 800
